# see travis-ci.org for details

sudo: false

language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install -y libtirpc-dev libwrap0-dev libselinux-dev

script:
  - sh autogen.sh
  - ./configure
  - make
  - make distcheck
