# see travis-ci.org for details

sudo: false

language: c

compiler:
  - clang
  - gcc

install:
  - libtirpc-dev
  - libwrap0-dev
  - libselinux-dev

script:
  - sh autogen.sh
  - ./configure
  - make
  - make distcheck
